jobs:
      
  - name: dd-man1cnrimg
    type: manifest
    steps:
      - IN: dd-image1
      - IN: dd-tg1
    on_start:
      - NOTIFY: dd-email
      - NOTIFY: dd-slack
    on_success:
      - NOTIFY: dd-email
      - NOTIFY: dd-slack
    flags: 
      - plv2-notifications_deletedeploy-pm6374_rSync
      
  - name: dd-man2
    type: manifest
    steps:
      - IN: dd-image3
      - IN: dd-tg2
    flags: 
      - dd-man2
 
  - name: dd-man3
    type: manifest
    steps:
      - IN: dd-image1
      - IN: dd-tg3
    flags:
      - dd-man3

      
# DEPLOYMENTS 

  - name: ddnotify-ecsdeployup
    type: deploy
    steps:
      - IN: sen-man2invalid
      - IN: sen-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: dd-email
      - NOTIFY: dd-slack
    on_failure:
      - NOTIFY: dd-email
      - NOTIFY: dd-slack
        
  - name: dd-ecsdeployup1
    type: deploy
    steps:
      - IN: dd-man2
      - IN: dd-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: dd-ecsdeploybg1
    type: deploy
    steps:
      - IN: dd-man3
      - IN: dd-ecscluster
        
