triggers:
   - name: triggernotify1
     type: trigger
     version:
       counter: 5
       
   - name: triggernotify2
     type: trigger
     version:
       counter: 3
       
   - name: triggernotify3
     type: trigger
     version:
       counter: 3
