jobs:

#RELEASE

  - name: notify-release
    type: release
    steps:
      - IN: notify-version
      - TASK: managed
        bump: patch
      - IN: notify-man1cnrimg
      - IN: triggernotify7
      
#MANIFESTS
      
  - name: notify-man1cnrimg
    type: manifest
    steps:
      - IN: notify-image1cnr
      - IN: triggernotify1
      
  - name: notify-man2entrypoint
    type: manifest
    steps:
      - IN: notify-image4entrypoint
      - TASK: managed
      - IN: triggernotify2
      
  - name: notify-man3driftking
    type: manifest
    steps:
      - IN: notify-image5workingdir
      - IN: triggernotify3
      - TASK: managed
    
  - name: notify-man4env
    type: manifest
    steps:
      - IN: notify-image3env
      - IN: triggernotify1  
  
  - name: notify-man5redis
    type: manifest
    steps:
      - IN: notify-image6redis
      - IN: triggernotify5
      
  - name: notify-man6invalid
    type: manifest
    steps:
      - IN: notify-image7new 
      #- IN: notify-dopts6invalid
      - IN: triggernotify6
      
  - name: notify-man7scale
    type: manifest
    steps:
      - IN: notify-image1cnr
      - IN: notify-scale1
      - IN: triggernotify8
      
  - name: notify-man8
    type: manifest
    steps:
      - IN: notify-image4entrypoint
      #- IN: notify-dopts6invalid
      - IN: triggernotify9
      
  - name: notify-man9
    type: manifest
    steps:
      - IN: notify-image4entrypoint
     # - IN: notify-dopts6invalid
      #- IN: notify-scale3
      - IN: triggernotify10
      
  - name: notify-man10
    type: manifest
    steps:
      - IN: notify-image4entrypoint
      #- IN: notify-dopts6invalid
      - IN: triggernotify11
      
  - name: notifyscale-man11
    type: manifest
    steps:
      - IN: notify-image1cnr
      - IN: notify-dopts1
      - IN: notifyd-scale4
      - IN: triggernotify12
      
  - name: notifyscale-man12
    type: manifest
    steps:
      - IN: notify-image1cnr
      #- IN: notify-dopts1
      #- IN: notifyd-scale4
      - IN: triggernotify13
      
  - name: notifydcl-man13
    type: manifest
    steps:
      - IN: notify-image5workingdir
      #- IN: notify-dopts1
      #- IN: notifyd-scale4
      - IN: triggernotify14

# DEPLOYMENTS 

  - name: notify-ecsdeployup
    type: deploy
    steps:
      - IN: notify-man3driftking
      - IN: notify-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: notifyup-ecsdeploy2
    type: deploy
    steps:
      - IN: notify-man8
      - IN: notify-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: notifyup2-ecsdeploy3
    type: deploy
    steps:
      - IN: notifyscale-man11
      - IN: notify-ecscluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: notify-ecsdeploybg
    type: deploy
    steps:
      - IN: notify-man1cnrimg
      - IN: notify-ecscluster
      
  - name: notifyscale-ecsdeploybg2
    type: deploy
    steps:
      - IN: notify-man7scale
      - IN: notifyd-scale4
      - IN: notify-ecscluster
      
  - name: notify-tripubdeployup
    type: deploy
    steps:
      - IN: notify-man3driftking
      - IN: notify-tripubcluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: notify-tripubdeploybg
    type: deploy
    steps:
      - IN: notify-man1cnrimg
      - IN: notify-tripubcluster
      
  - name: notifybg-tpdeploy2
    type: deploy
    steps:
      - IN: notify-man10
      - IN: notify-tripubcluster
      
  - name: notifyup-tripubdeploy2
    type: deploy
    steps:
      - IN: notify-man6invalid
      - IN: notify-tripubcluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: notifyup-tpdeploy3
    type: deploy
    steps:
      - IN: notify-man5redis
      #- IN: notify-dopts6invalid
      - IN: notify-tripubcluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: notifyup1-tpdeploy4
    type: deploy
    steps:
      - IN: notifyscale-man12
      - IN: notifyd-scale4
      #- IN: notify-dopts6invalid
      - IN: notify-tripubcluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: notify-gkedeployup
    type: deploy
    steps:
      - IN: notify-man3driftking
      - IN: notify-gkecluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: notifyup-gkedeploy2
    type: deploy
    steps:
      - IN: notify-man9
      - IN: notify-gkecluster
      - TASK: managed
        deployMethod: upgrade
    
  - name: nscale-gkedup2
    type: deploy
    steps:
      - IN: notify-man7scale
      - IN: notifyd-scale4
      - IN: notify-gkecluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: notify-gkedeploybg
    type: deploy
    steps:
      - IN: notify-man1cnrimg
      - IN: notify-gkecluster
      
  - name: notify-dcldeploy
    type: deploy
    steps:
      - IN: notify-man3driftking
      - IN: notify-dopts1
      - IN: notify-scale1
      - IN: notify-dclcluster
      
  - name: notify-dcldeploy2
    type: deploy
    steps:
      - IN: notifydcl-man13
      - IN: notify-dclcluster
        
  - name: notify-ddcdeploy
    type: deploy
    steps:
      - IN: notify-man3driftking
      - IN: notify-ddccluster
      #- TASK: managed
