jobs:
  - name: sen-release
    type: release
    steps:
      - IN: sen-version
      - TASK: managed
        bump: beta
      - IN: sen-man1cnrimg
      - IN: triggersen1
    on_start:
      - NOTIFY: sen-emailcock1
      - NOTIFY: sen-slackcock1
    on_success:
      - NOTIFY: sen-emailcock1
      - NOTIFY: sen-slackcock1
      
  - name: sen-man1cnrimg
    type: manifest
    steps:
      - IN: sen-image1cnr
      - IN: triggersen2
    on_start:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
    on_success:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
      
  - name: sen-man2invalid
    type: manifest
    steps:
      - IN: sen-image2entrypoint
      - IN: sen-dopts1invalid
      - IN: triggersen3

# DEPLOYMENTS 

  - name: sen-ecsdeployup1
    type: deploy
    steps:
      - IN: sen-man2invalid
      - IN: sen-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
    on_failure:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
