triggers:
   - name: triggernotify1
     type: trigger
     version:
       counter: 3
       
   - name: triggernotify2
     type: trigger
     version:
       counter: 3
       
   - name: triggernotify3
     type: trigger
     version:
       counter: 5
       
   - name: triggernotify4
     type: trigger
     version:
       counter: 3
       
   - name: triggernotify5
     type: trigger
     version:
       counter: 2
       
   - name: triggernotify6
     type: trigger
     version:
       counter: 7
       
   - name: triggernotify7
     type: trigger
     version:
       counter: 1
       
   - name: triggernotify8
     type: trigger
     version:
       counter: 7
