triggers:
   - name: triggeren1
     type: trigger
     version:
       counter: 2
       
   - name: triggeren2
     type: trigger
     version:
       counter: 2
       
   - name: triggeren3
     type: trigger
     version:
       counter: 3
