jobs:
  - name: en-release
    type: release
    steps:
      - IN: en-version
      - TASK: managed
        bump: beta
      - IN: en-man1cnrimg
      - IN: triggeren1
    on_start:
      - NOTIFY: en-emailcock1
      - NOTIFY: en-slackcock1
    on_success:
      - NOTIFY: en-emailcock1
      - NOTIFY: en-slackcock1
      
  - name: en-man1cnrimg
    type: manifest
    steps:
      - IN: en-image1cnr
      - IN: triggeren2
    on_start:
      - NOTIFY: en-email
      - NOTIFY: en-slack
    on_success:
      - NOTIFY: en-email
      - NOTIFY: en-slack
      
  - name: en-man2invalid
    type: manifest
    steps:
      - IN: en-image2entrypoint
      - IN: en-dopts1invalid
      - IN: triggeren3

        
