triggers:
   - name: dd-tg1
     type: trigger
     version:
       counter: 0
       
   - name: dd-tg2
     type: trigger
     version:
       counter: 1
       
   - name: dd-tg3
     type: trigger
     version:
       counter: 1
       
   - name: dd-tg4
     type: trigger
     version:
       counter: 0
       
   - name: dd-tg5
     type: trigger
     version:
       counter: 0
