triggers:
   - name: triggersen1
     type: trigger
     version:
       counter: 2
       
   - name: triggersen2
     type: trigger
     version:
       counter: 2
       
   - name: triggersen3
     type: trigger
     version:
       counter: 2
