triggers:
   - name: triggernotify1
     type: trigger
     version:
       counter: 3
       
   - name: triggernotify2
     type: trigger
     version:
       counter: 3
       
   - name: triggernotify3
     type: trigger
     version:
       counter: 7
       
   - name: triggernotify4
     type: trigger
     version:
       counter: 3
       
   - name: triggernotify5
     type: trigger
     version:
       counter: 5
       
   - name: triggernotify6
     type: trigger
     version:
       counter: 7
       
   - name: triggernotify7
     type: trigger
     version:
       counter: 1
       
   - name: triggernotify8
     type: trigger
     version:
       counter: 7
       
   - name: triggernotify9
     type: trigger
     version:
       counter: 5
       
   - name: triggernotify10
     type: trigger
     version:
       counter: 8
       
   - name: triggernotify11
     type: trigger
     version:
       counter: 5
       
   - name: triggernotify12
     type: trigger
     version:
       counter: 7
       
   - name: triggernotify13
     type: trigger
     version:
       counter: 1
