jobs:
  - name: notify-release
    type: release
    steps:
      - IN: notify-version
      - TASK: managed
        bump: patch
      - IN: notify-man1
      - IN: triggernotify2
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-emailcock1
    on_success:
      - NOTIFY: notify-emailcock1
      - NOTIFY: notify-emailvarsha
      - NOTIFY: notify-slack
      
  - name: notify-man1
    type: manifest
    steps:
      - IN: notify-imagerunc1
      - IN: triggernotify3
      - IN: notify-dopts
      
  - name: notify-man2
    type: manifest
    steps:
      - IN: notify-imageinvalid
      - IN: triggernotify1
      - IN: notify-dopts
    on_start:
      - NOTIFY: notify-emailcock1
      - NOTIFY: notify-slack2
    on_success:
      - NOTIFY: notify-emailcock1
      - NOTIFY: notify-slack2
      
  - name: notify-man3
    type: manifest
    steps:
      - IN: notify-imagerunc2
      - IN: triggernotify4
      
  - name: notify-man4
    type: manifest
    steps:
      - IN: notify-imagerunc2
      - IN: triggernotify5
      
  - name: notify-man5
    type: manifest
    steps:
      - IN: notify-imagerunc2
      - IN: triggernotify6
      
  - name: notify-ecsdeploy
    type: ecsDeploy
    steps:
      - IN: notify-man1
      - IN: notify-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-emailcock1
    on_success:
      - NOTIFY: notify-slack
      - NOTIFY: notify-emailcock1
    on_failure:
      - NOTIFY: notify-slack
      - NOTIFY: notify-emailcock1
      
  - name: notify-ecsdeployup1
    type: deploy
    steps:
      - IN: notify-man3
      - IN: notify-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: notify-ecsdeploybg1
    type: deploy
    steps:
      - IN: notify-man4
      - IN: notify-ecscluster
      
  - name: notify-ecsdeploybg2
    type: deploy
    steps:
      - IN: notify-man5
      - IN: notify-ecscluster2
