jobs:
  - name: notify-release
    type: release
    steps:
      - IN: notify-version
      - TASK: managed
        bump: patch
      - IN: notify-man1
      - IN: triggernotify2
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-emailcock1
    on_success:
      - NOTIFY: notify-emailcock1
      - NOTIFY: notify-emailvarsha
      - NOTIFY: notify-slack
      
  
