jobs:
  - name: notify-release
    type: release
    steps:
      - IN: notify-version
      - TASK: managed
        bump: patch
      - IN: notify-man1cnrimg
      - IN: triggernotify7
      
  - name: notify-man1cnrimg
    type: manifest
    steps:
      - IN: notify-image1cnr
      - IN: triggernotify1
      
  - name: notify-man2entrypoint
    type: manifest
    steps:
      - IN: notify-image4entrypoint
      - TASK: managed
      - IN: triggernotify2
      
  - name: notify-man3driftking
    type: manifest
    steps:
      - IN: notify-image5workingdir
      - IN: triggernotify3
      - TASK: managed
    
  - name: notify-man4env
    type: manifest
    steps:
      - IN: notify-image3env
      - IN: triggernotify1  
  
  - name: notify-man5redis
    type: manifest
    steps:
      - IN: notify-image6redis
      - IN: triggernotify5
      
  - name: notify-man6invalid
    type: manifest
    steps:
      - IN: notify-image3env
      - IN: notify-dopts6invalid
      - IN: triggernotify6

# DEPLOYMENTS 

  - name: notify-ecsdeployup
    type: deploy
    steps:
      - IN: notify-man3driftking
      - IN: notify-ecscluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: notify-ecsdeploybg
    type: deploy
    steps:
      - IN: notify-man1cnrimg
      - IN: notify-ecscluster
      
  - name: notify-tripubdeployup
    type: deploy
    steps:
      - IN: notify-man3driftking
      - IN: notify-tripubcluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: notify-tripubdeploybg
    type: deploy
    steps:
      - IN: notify-man1cnrimg
      - IN: notify-tripubcluster
      
  - name: notify-gkedeployup
    type: deploy
    steps:
      - IN: notify-man3driftking
      - IN: notify-gkecluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: notify-gkedeploybg
    type: deploy
    steps:
      - IN: notify-man1cnrimg
      - IN: notify-gkecluster
      
  - name: notify-dcldeployup
    type: deploy
    steps:
      - IN: notify-man3driftking
      - IN: notify-dclcluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: notify-dcldeploybg
    type: deploy
    steps:
      - IN: notify-man1cnrimg
      - IN: notify-dclcluster
