jobs:
      
  - name: dd-man1cnrimg
    type: manifest
    steps:
      - IN: dd-image1
      - IN: dd-tg1
    on_start:
      - NOTIFY: dd-email
      - NOTIFY: dd-slack
    on_success:
      - NOTIFY: dd-email
      - NOTIFY: dd-slack
      
  - name: dd-man2
    type: manifest
    steps:
      - IN: dd-image3
      - IN: dd-tg2
      
# DEPLOYMENTS 

  - name: ddnotify-ecsdeployup
    type: deploy
    steps:
      - IN: sen-man2invalid
      - IN: sen-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
    on_failure:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
        
  - name: dd-ecsdeployup1
    type: deploy
    steps:
      - IN: 
      - IN: sen-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
