jobs:
  - name: sen-release
    type: release
    steps:
      - IN: sen-version
      - TASK: managed
        bump: beta
      - IN: sen-man1cnrimg
      - IN: triggersen1
    on_start:
      - NOTIFY: sen-emailcock1
      - NOTIFY: sen-slackcock1
    on_success:
      - NOTIFY: sen-emailcock1
      - NOTIFY: sen-slackcock1
      
  - name: sen-man1cnrimg
    type: manifest
    steps:
      - IN: sen-image1cnr
      - IN: triggersen2
    on_start:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
    on_success:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
      
  - name: sen-man2invalid
    type: manifest
    steps:
      - IN: sen-image2entrypoint
      - IN: sen-dopts1invalid
      - IN: triggersen3
      
  - name: sen-man3
    type: manifest
    steps:
      - IN: sen-image1cnr
      - IN: triggersen4

# DEPLOYMENTS 

  - name: sen-ecsdeployup2
    type: deploy
    steps:
      - IN: sen-man2invalid
      - IN: sen-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
    on_failure:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
      
  - name: sen-ecsdeployup3
    type: deploy
    steps:
      - IN: sen-man3cnrimg
      - IN: sen-ecscluster2invalid
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
    on_failure:
      - NOTIFY: sen-email
      - NOTIFY: sen-slack
      
  - name: sen-ecsdeployup4
    type: deploy
    steps:
      - IN: sen-man3
      - IN: sen-ecscluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: sen-release2
    type: release
    steps:
      - IN: sen-version2
      - IN: sen-ecsdeployup4
      - TASK: managed
        bump: beta
        
  - name: sen-ecsdeployup5
    type: deploy
    steps:
      - IN: sen-release2
      - IN: sen-ecscluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: sen-release3
    type: release
    steps:
      - IN: sen-version3
      - IN: sen-ecsdeployup5
      - TASK: managed
        bump: major
        
