triggers:
   - name: triggersen1
     type: trigger
     version:
       counter: 2
       
   - name: triggersen2
     type: trigger
     version:
       counter: 2
       
   - name: triggersen3
     type: trigger
     version:
       counter: 3
       
   - name: triggersen4
     type: trigger
     version:
       counter: 4
       
   - name: triggersen5
     type: trigger
     version:
       counter: 3
       
   - name: triggersen6
     type: trigger
     version:
       counter: 1
       
   - name: triggersen7
     type: trigger
     version:
       counter: 1
