jobs:
  - name: notify-release
    type: release
    steps:
      - IN: notify-version
      - TASK: managed
        bump: patch
      - IN: notify-man1
      - IN: triggernotify2
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-emailcock1
    on_success:
      - NOTIFY: notify-emailcock1
      - NOTIFY: notify-emailvarsha
      - NOTIFY: notify-slack
      
  - name: notify-man1
    type: manifest
    steps:
      - IN: notify-imagerunc1
      - IN: triggernotify3
      - IN: notify-dopts
      
  - name: notify-man2
    type: manifest
    steps:
      - IN: notify-imageinvalid
      - IN: triggernotify1
      - IN: notify-dopts
      
  - name: notify-ecsdeploy
    type: ecsDeploy
    steps:
      - IN: notify-man1
      - IN: notify-ecscluster
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-emailcock1
    on_success:
      - NOTIFY: notify-slack
      - NOTIFY: notify-emailcock1
    on_failure:
      - NOTIFY: notify-slack
      - NOTIFY: notify-emailcock1
      
